### ISSUE TITLE
WP 3.8 / MP6 Switch Requires Icon Font Menu Icon

### ISSUE THREAD

**Issue by mrwweb** [markjaquith/wp-help#13]
With the switch to WordPress 3.8 and the default dark color scheme, the plugin's menu icon no longer works. The plugin should switch to a font-based icon. Either a "?" or the equivalent symbol from Dashicons (content: "\f223";) makes sense.

This CSS adds the dashicon:

``` css
.toplevel_page_wp-help-documents .wp-menu-image:before {
    content: "\f223";
}
```

Such a switch would also require removing the current icon from the `add_menu_icon()` call that adds the Publishing Help admin menu item.

The plugin could maintain backwards compatibility by either only added the icon to the menu in 3.8+ or loading the Dashicon font in <3.8.
